# -*- fill-column: 80; org-confirm-babel-evaluate: nil -*-

#+TITLE:     Assignment 11, Discrete Mathematics
#+AUTHOR:    Oleg Sivokon
#+EMAIL:     olegsivokon@gmail.com
#+DATE:      <2015-03-21 Sat>
#+DESCRIPTION: First asssignment in the course Discrete Mathematics
#+KEYWORDS: Discrete Mathematics, Assignment, Set Theory
#+LANGUAGE: en
#+LaTeX_CLASS: article
#+LATEX_HEADER: \usepackage[usenames,dvipsnames]{color}
#+LATEX_HEADER: \usepackage[backend=bibtex, style=numeric]{biblatex}
#+LATEX_HEADER: \usepackage{commath}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usetikzlibrary{shapes,backgrounds}
#+LATEX_HEADER: \usepackage{marginnote}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \usepackage{enumerate}
#+LATEX_HEADER: \hypersetup{urlcolor=blue}
#+LATEX_HEADER: \hypersetup{colorlinks,urlcolor=blue}
#+LATEX_HEADER: \addbibresource{bibliography.bib}
#+LATEX_HEADER: \setlength{\parskip}{16pt plus 2pt minus 2pt}
#+LATEX_HEADER: \definecolor{codebg}{rgb}{0.96,0.99,0.8}
#+LATEX_HEADER: \definecolor{codestr}{rgb}{0.46,0.09,0.2}

#+BEGIN_SRC emacs-lisp :exports none
(setq org-latex-pdf-process
        '("latexmk -pdflatex='pdflatex -shell-escape -interaction nonstopmode' -pdf -bibtex -f %f")
        org-latex-listings t
        org-src-fontify-natively t
        org-babel-latex-htlatex "htlatex")
(defmacro by-backend (&rest body)
    `(cl-case (when (boundp 'backend) (org-export-backend-name backend))
       ,@body))
#+END_SRC

#+RESULTS:
: by-backend

#+BEGIN_LATEX
  \lstset{ %
    backgroundcolor=\color{codebg},
    basicstyle=\ttfamily\scriptsize,
    breakatwhitespace=false,         % sets if automatic breaks should only happen at whitespace
    breaklines=false,
    captionpos=b,                    % sets the caption-position to bottom
    commentstyle=\color{mygreen},    % comment style
    framexleftmargin=10pt,
    xleftmargin=10pt,
    framerule=0pt,
    frame=tb,                        % adds a frame around the code
    keepspaces=true,                 % keeps spaces in text, useful for keeping indentation of code (possibly needs columns=flexible)
    keywordstyle=\color{blue},       % keyword style
    showspaces=false,                % show spaces everywhere adding particular underscores; it overrides 'showstringspaces'
    showstringspaces=false,          % underline spaces within strings only
    showtabs=false,                  % show tabs within strings adding particular underscores
    stringstyle=\color{codestr},     % string literal style
    tabsize=2,                       % sets default tabsize to 2 spaces
  }
#+END_LATEX

\clearpage

* Problems

** Problem 1
   In all questions that follow, establish whether $x \in y$ or $x \subseteq y$.
   1. $x = \{1, 2\}, y = \{1, 2, 3\}$.
   2. $x = \{3\}, y = \{\{1\}, \{2\}, \{3\}\}$.
   3. $x = \{1, 2\}, y = \{\{1, 2\}, 3\}$.
   4. $x = \{1, 3\}, y = \{\{1, 2\}, 3\}$.
   5. $x = \emptyset, y = \emptyset$.
   6. $x = \{\emptyset\}, y = \{\emptyset\}$.
   7. $x = \{1\}, y = \{1, 2\}$.
   8. $x = \emptyset, y = P(\{1, 2, 3\})$.

*** Answer 1
    1. $x \subseteq y$.
    2. $x \in y$.
    3. $x \in y$.
    4. $x \not \in y \land x \not \subseteq y$.
    5. $x \subseteq y$.
    6. $x \subseteq y$.
    7. $x \subseteq y$.
    8. $x \subseteq y$.

** Problem 2
   Prove or disprove:
   1. $(A \setminus B) \setminus B = A \setminus B$.
   2. $A \setminus (B \setminus A) = A$.
   3. $A \subseteq P(A)$.

*** Answer 2
    The statement is true.  Suppose for contradiction that there is a $b \in A
    \setminus B$ s.t. $b \not \in (A \setminus B) \setminus B$.  Then, we know
    that $b \in A$ and $b \not \in B$.  But we assumed $b \not \in A \lor b \in
    B$.  This is a contradiction, hence $(A \setminus B) \setminus B = A
    \setminus B$.  Additionally, it is easy to see that set subtraction is
    idempotent (i.e. if applied repeatedly, will yield the same result after
    first application).

*** Answer 3
    The statement is true.  Suppose for contradiction there was an $a \in A$,
    which is not in $A \setminus (B \setminus A)$.  Then such $a$ would have
    to be in $A$, but not in $(B \setminus A)$.  I will now show that no elements
    of $(B \setminus A)$ is in $A$, thus subtracting this group would not
    remove any elements of $A$, i.e. $A \cap (B \setminus A) = \emptyset$.
    Suppose $b$ was in $A$ and in $(B \setminus A)$ at the same time, then
    it would have to be in $A$, but $A$ is excluded from $(B \setminus A)$.
    This is in contradiction to the previous assumtion.  Therefore
    $A \setminus (B \setminus A) = A$.

*** Answer 4
    This statement isn't true in general.  An example which disproves it would
    be an assignment: $A=\{1, 2\}$.  $P(A)=\{\emptyset, \{1\}, \{2\}, \{1, 2\}\}$.
    $A \not \subseteq P(A)$.

** Problem 3
   Prove the following identity using $A \setminus B = A \cap B'$:
   $(A_1 \cup A_2) \setminus (B_1 \cap B_2) = (A_1 \cup B_1) \cup (A_1 \cup B_2)
   \cup (A_2 \cup B_1) \cup (A_2 \cup B_2)$.

*** Answer 5
    The proof doesn't require discussion.  It is accomplished by simple
    set-theoretical manipulations.
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          (A_1 \cup A_2) \setminus (B_1 \cap B_2) &\iff
          &\textrm{Given} \\
          A_1 \setminus (B_1 \cap B_2) \cup A_2 \setminus (B_1 \cap B_2) &\iff
          &\textrm{Union over subtraction} \\
          A_1 \cap (B_1 \cap B_2)' \cup A_2 \cap (B_1 \cap B_2)' &\iff
          &\textrm{Required identity} \\
          A_1 \cap (B_1' \cup B_2') \cup A_2 \cap (B_1' \cup B_2') &\iff
          &\textrm{De Morgan's law} \\
          (A_1 \cap B_1') \cup (A_1 \cap B_2') \cup
          (A_2 \cap B_1') \cup (A_2 \cap B_2') &\iff
          &\textrm{Union over subtraction} \\
          (A_1 \setminus B_1) \cup (A_1 \setminus B_2)
          \cup (A_2 \setminus B_1) \cup (A_2 \setminus B_2) &\iff
          &\textrm{Required identity}
        \end{aligned}
      \end{equation*}
    #+END_SRC
