# -*- fill-column: 80; org-confirm-babel-evaluate: nil -*-

#+TITLE:     Assignment 12, Discrete Mathematics
#+AUTHOR:    Oleg Sivokon
#+EMAIL:     olegsivokon@gmail.com
#+DATE:      <2015-04-05 Sun>
#+DESCRIPTION: Second asssignment in the course Discrete Mathematics
#+KEYWORDS: Discrete Mathematics, Assignment, Relations
#+LANGUAGE: en
#+LaTeX_CLASS: article
#+LATEX_HEADER: \usepackage[usenames,dvipsnames]{color}
#+LATEX_HEADER: \usepackage[backend=bibtex, style=numeric]{biblatex}
#+LATEX_HEADER: \usepackage{commath}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usetikzlibrary{shapes,backgrounds}
#+LATEX_HEADER: \usepackage{marginnote}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \usepackage{enumerate}
#+LATEX_HEADER: \hypersetup{urlcolor=blue}
#+LATEX_HEADER: \hypersetup{colorlinks,urlcolor=blue}
#+LATEX_HEADER: \addbibresource{bibliography.bib}
#+LATEX_HEADER: \setlength{\parskip}{16pt plus 2pt minus 2pt}
#+LATEX_HEADER: \definecolor{codebg}{rgb}{0.96,0.99,0.8}
#+LATEX_HEADER: \definecolor{codestr}{rgb}{0.46,0.09,0.2}

#+BEGIN_SRC emacs-lisp :exports none
(setq org-latex-pdf-process
        '("latexmk -pdflatex='pdflatex -shell-escape -interaction nonstopmode' -pdf -bibtex -f %f")
        org-latex-listings t
        org-src-fontify-natively t
        org-babel-latex-htlatex "htlatex")
(defmacro by-backend (&rest body)
    `(cl-case (when (boundp 'backend) (org-export-backend-name backend))
       ,@body))
#+END_SRC

#+RESULTS:
: by-backend

#+BEGIN_LATEX
  \lstset{ %
    backgroundcolor=\color{codebg},
    basicstyle=\ttfamily\scriptsize,
    breakatwhitespace=false,         % sets if automatic breaks should only happen at whitespace
    breaklines=false,
    captionpos=b,                    % sets the caption-position to bottom
    commentstyle=\color{mygreen},    % comment style
    framexleftmargin=10pt,
    xleftmargin=10pt,
    framerule=0pt,
    frame=tb,                        % adds a frame around the code
    keepspaces=true,                 % keeps spaces in text, useful for keeping indentation of code (possibly needs columns=flexible)
    keywordstyle=\color{blue},       % keyword style
    showspaces=false,                % show spaces everywhere adding particular underscores; it overrides 'showstringspaces'
    showstringspaces=false,          % underline spaces within strings only
    showtabs=false,                  % show tabs within strings adding particular underscores
    stringstyle=\color{codestr},     % string literal style
    tabsize=2,                       % sets default tabsize to 2 spaces
  }
#+END_LATEX

\clearpage

* Problems

** Problem 1
   Let $M$ be the set of all relations over $A=\{1, 2, 3\}$.
   1. How many members does $M$ have?
   2. Let $S$ be a set of relations over $M$, defined as follows:
      #+HEADER: :exports results
      #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
      #+BEGIN_SRC latex
        \begin{equation*}
          S=\{R_1R_2 | R_1, R_2 \in M \land R_1R_2 = R_2R_1\}.
        \end{equation*}
      #+END_SRC
      Show that $S$ is not an equivalence relation.

*** Answer 1
    The number of elements of $M$ is $2^{\left|A\right|^2} = 2^{3^2} = 2^9
    = 512$.  This can be proved from a partial sum of a recurence: $a_{n+1} =
    a_n + 2n - 1$, which describes the maximum number of ordered pairs possible
    to create from $n$ elements and $b_n = 2b_{n-1}$ recurrence which describes
    the number of elements of a powerset.  Since one can see that the number
    of relations over a set is exactly the number of ways to subset the set of
    all ordered pairs possible to create from that set, the final answer is
    the composition of both recurrences: $c_n=b_n \circ a_n$.

    Below I've implemented the counting algorithm in Prolog:

    #+HEADER: :system swipl :exports both :results raw
    #+HEADER: :goal question_1([1, 2, 3]).
    #+BEGIN_SRC prolog
      powerset(Set, Result) :-
          powerset_helper(Set, [[]], Result).
      powerset_helper([], X, X) :- !.
      powerset_helper([X | Xs], In, Result) :-
          findall(Z, (member(Y, In), append([X], Y, Z)), Z),
          append(In, Z, Next),
          powerset_helper(Xs, Next, Result).
      
      cross(Set, (A, B)) :- member(A, Set), member(B, Set).
      
      pairs(Set, Pairs) :- findall(X, cross(Set, X), Pairs).
      
      question_1(A) :-
          pairs(A, Pairs),
          powerset(Pairs, M),
          length(M, Len),
          format("$\\left|M\\right| = ~p$~n", [Len]).
    #+END_SRC

*** Answer 2
    I will prove that $S$ is not an equivalence using the definition of
    equivalence which states that a relation is an equivalence if it is
    *relfexive*, *symmetric* and *transitive*.  It is easy to see that the
    definition of reflexivity requires that /all/ members of $M$ be present in
    the relation, but, for example, $\{(1, 2)\}$ is absent from $S$.  Suppose,
    for contradiction, it was present in $S$, then it would imply that there
    exists a pair $\{(a, b)\} \in M$ s.t. $(\{(1, 2)\}, \{(a, b)\}) \in S$ and
    $(\{(a, b)\}, \{(1, 2)\}) \in\nobreak S$.  By looking at the first and the
    last members of the two members of $S$ we know that $\{(1, 2)\} \circ \{(a,
    b)\} = \{(1, b)\}$ and $\{(a, b)\} \circ \{(1, 2)\} = \{(a, 2)\}$, in other
    words it is necessary that: $\{(1, 2)\} \circ \{(a, b)\} = \{(1, b)\} =
    \{(1, 2)\} = \{(a, 2)\} = \{(a, b)\} \circ \{(1, 2)\}$, which in turn, means
    that $b=2$ and $a=1$.  Plugging these values back into original equilaty
    gives $\{(1, 2)\} \circ \{(1, 2)\} = \{(1, 2)\}$, which is obviously false.
    Hence, by contradiction, the proof is complete.

** Problem 2
   Given a set $A=\{1, 2, 3\}$ and $M$ a set of all reations over $A$.  Let also
   $s : M \to M$ be a function assigning to each $R \in M$ its transitive
   closure ($R^{+}$).  Prove or disprove:
   1. $s$ is one-to-one.
   2. $s$ is onto.
   3. For all $R_1,R_2 \in M$ it holds that $s(R_1R_2) = s(R_1)s(R_2)$.
   4. For all $R \in M$ it holds that $s(R) = s(s(R))$.

*** Answer 3
    A function is one-to-one when if $s(x)=s(y)$ then it must also be that
    $x=y$.  From definition of transitive closure it follows that it may be
    closed over more than one set (i.e. it must be its own subset but may have
    more subsets which are not transitive relations).  Thus it's not true that
    $s(x) = s(y) \implies x=y$. To be more concrete, suppose this example:
    $R_1=\{(1, 2), (1, 3)\}$ and $R_2=\{(1, 2), (2, 3)\}$.
    Then $s(R_1)=\{(1, 2), (1, 3), (2, 3)\}$ and $s(R_2)=\{(1, 2), (2, 3), (1, 3)\}$.
    Thus $s$ is not one-to-one.

*** Answer 4
    Recall the definition of a function which is onto: for each element in the
    function's co-domain there exists an element in its domain.  Using the
    definition of transitive closure, every such closure contains at least one
    relation (itself), thus $s$ has an element in its domain for each element in
    its co-domain.  Thus the claim is true.

*** Answer 5
    This is not in general true, consider $R_1$ to be $\{(1,1), (1,2), (1,3)\}$
    and $R_2=\{(3,3)\}$.  Then:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{eqnarray*}
        s(R_1R_2)    &= s(\{(1,3)\})                                   &= \{(1,3)\} \\
        s(R_1)s(R_2) &= \{(1,1), (1,2), (2,3), (1,3)\} \circ \{(3,3)\} &= \{(2,3), (1,3)\}.
      \end{eqnarray*}
    #+END_SRC

*** Answer 6
    It is true that $s$ is /idempotent/. This is so because for any transitive
    relation its transitive closure is equal to it and the co-domain of $s$ is
    defined to contain only transitive relations.

** Problem 3
   Let $F$ be the set of functions from $\mathbb{N}$ to itself.  Define relation
   $K$ over $F$ s.t. $f, g \in F, (f, g) \in K \iff \forall n \in \mathbb{N} f(n) \leq g(n)$.
   1. Prove that $K$ is a partially ordered.
   2. Prove that $K$ isn't totally ordered.
   3. Are there maximal members in $K$? Is there a largest member in $K$?
   4. Are there minimal members in $K$? Is there a smallest member in $K$?
   5. Prove that for any $f \in F$ exists $g \in F$ bounding it from above.
      Prove there are more than one such $g$.

*** Answer 7
    Partially ordered sets are defined to be reflexive, antisymmetrical and
    transitive. Let's verify all these properties:
    + Reflexitivty :: $f(n) \leq f(n)$ is true because the co-domains of $f$ and
      $g$ are the set of natural numbers, for which this property also holds, besides,
      we required that the inequality holds for each value of the functions taken
      pair-wise.
    + Antisymmetry :: whenever $f(n) \leq g(n)$ and $f(n) \leq g(n)$
      then $f(n) = g(n)$.  By the same reasoning as above, $K$ is antisymmetrical.
    + Transitivity :: if $f(n) \leq g(n)$ and $q(n) \leq f(n)$, then $q(n) \leq g(n)$.
      And, again, since the co-domain of all these functions is the natural numbers
      transitivity holds.
      
    Thus $K$ is partially ordered.

*** Answer 8
    To say that $K$ isn't totally ordered is to say that there exists a pair of
    functions $f'$ and $g'$ such that for them neither $f'(n) \leq g'(n)$ nor
    $g'(n) \leq f'(n)$ for all $n \in \mathbb{N}$.  Any two functions, whose graphs
    cross will do the job (before the interesection point one of the functions
    will be greater than the other and after the intersection the relation will
    change sides).  So, for example functions $g'(n)=n^2$ and $f'(n)=n+2$ are
    $g'(n) < f'(n)$ when $n < 2$ and $g'(n) > f'(n)$ otherwise.

*** Answer 9
    No, there isn't a maximal element in $K$ since there isn't a maximal element
    in the natrual numbers (and natural numbers are the co-domain of the functions
    used to construct $K$). Consequently, there isn't a largest element in $K$.

*** Answer 10
    However, there is a minimal element in $K$ (and subsequently the smallest one).
    It is $(x(n)=0, x(n)=0)$.  It is easy to see that this element is in $K$,
    since it is a function from $\mathbb{N}$ to itself, also both elements of the
    pair adhere to the condition that they'd be no greater for all $n \in \mathbb{N}$.
    It is also easy to see that there is no pair which is not strictly greater
    than this element.  Suppose, for contradiction, there was such a pair, then
    for some natural number $n$, the $x'(n) \leq x(n) = 0$, but 0 is the smallest
    element of $\mathbb{N}$, contrary to assumed.  Thus there is a smallest element
    and the set of minimal elements (consisting of the smallest element).

*** Answer 11
    Suppose for contradiction there was an $x(n)$ which wasn't bounded above by any
    $y(n)$.  Then its value at $n$ would be some $m \in \mathbb{N}$, but we can
    construct $y(n)=x(n)+1$, in contradiction to our initial assumption.  Thus
    every element in $K$ must be bounded from above.  Observe also that the bounds
    themselves are members of $K$, and since they are, then each bound has its own
    bound, and by transitivity of the relation ``the upper bound of'' we can see
    that every member of $K$ has infinitely many such bounds.

** Problem 4
   1. Prove by induction that the following function definitions are equivalent:
      $f(0)=0$, $f(1)=10$, $f(n+2)=f(n+1)+6f(n)$. And $f(n)=2*3^n+(-2)^{n+1}$.
   2. Is the function defined above onto?

*** Answer 12
    Using mathematical induction, let's first verify the base step:
    $f(0)=0$ and $f(0)=2*3^0+(-2)^{1}=2-2=0$.

    Inductive step will first establish the relation between three subsequent
    terms of the sequence, and then verify that the same relation holds for
    both definition of $f$.
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{split}
          f(n + 3) &= f(n + 2) + 6f(n + 1) \\
                   &= f(n + 1) + 6f(n) + 6f(n + 1) \\
                   &= 7f(n + 1) + 6f(n) \\
          f(n + 3) - f(n + 2) &= 7f(n + 1) + 6f(n) - f(n + 1) - 6f(n) \\
                              &= 6f(n)
        \end{split}
      \end{equation*}
    #+END_SRC
    Now, I will use the induction hypothesis to demonstrate that $f(n+2)-f(n+1)=f(n)$:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{split}
          & f(n + 2) - f(n + 1) - 6f(n) = 0 \\
          & 2*3^{n+2} + (-2)^{n+3} - 2*3^{n+1} - (-2)^{n+2} - 6*2*3^n - (-2)^{n+1} = 0 \\
          & 2*3^{n+2} - 2*3^{n+1} - 6*2*3^n + (-2)^{n+3} - (-2)^{n+2} - (-2)^{n+1} = 0 \\
          & 2*3^{n+2} - 6*3^n - 6*2*3^n + \\
          & \hspace{4em} + (-2)*(-2)*(-2)^{n+1} - (-2)(-2)^{n+1} - 6*(-2)^{n+1} = 0 \\
          & 2*3^{n+2} - 3^n(6 + 6*2) + (-2)^{n+1}(4 - (-2) - 6) = 0 \\
          & 2*3^{n+2} - 3^n*2*9 + (-2)^{n+1}*0 = 0 \\
          & 0 + 0 = 0.
        \end{split}
      \end{equation*}
    #+END_SRC
    Having showed that the induction step holds too, using the principle of mathematical
    induction the proof is complete.

*** Answer 13
    Recall that in order to demonstrate that the function is not onto it is enough to find
    an element in its co-domain, which is not in its domain.  Suppose this function had
    a value in range $(0, 10)$, but since multiplication is preserving inequality and
    is non-decreasing, the value would have to be between zero and one, but there are no
    natural numbers between zero and one, hence the function is not onto.
