# -*- fill-column: 80; org-confirm-babel-evaluate: nil -*-

#+TITLE:     Assignment 13, Discrete Mathematics
#+AUTHOR:    Oleg Sivokon
#+EMAIL:     olegsivokon@gmail.com
#+DATE:      <2015-04-05 Sun>
#+DESCRIPTION: Third asssignment in the course Discrete Mathematics
#+KEYWORDS: Discrete Mathematics, Assignment, Relations
#+LANGUAGE: en
#+LaTeX_CLASS: article
#+LATEX_HEADER: \usepackage[usenames,dvipsnames]{color}
#+LATEX_HEADER: \usepackage{commath}
#+LATEX_HEADER: \usepackage{eufrak}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usetikzlibrary{shapes,backgrounds}
#+LATEX_HEADER: \usepackage{marginnote}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \usepackage{enumerate}
#+LATEX_HEADER: \hypersetup{urlcolor=blue}
#+LATEX_HEADER: \hypersetup{colorlinks,urlcolor=blue}
#+LATEX_HEADER: \setlength{\parskip}{16pt plus 2pt minus 2pt}
#+LATEX_HEADER: \definecolor{codebg}{rgb}{0.96,0.99,0.8}
#+LATEX_HEADER: \definecolor{codestr}{rgb}{0.46,0.09,0.2}

#+BEGIN_SRC emacs-lisp :exports none
(setq org-latex-pdf-process
        '("latexmk -pdflatex='pdflatex -shell-escape -interaction nonstopmode' -pdf -f %f")
        org-latex-listings t
        org-src-fontify-natively t
        org-babel-latex-htlatex "htlatex")
(defmacro by-backend (&rest body)
    `(cl-case (when (boundp 'backend) (org-export-backend-name backend))
       ,@body))
#+END_SRC

#+RESULTS:
: by-backend

#+BEGIN_LATEX
  \lstset{ %
    backgroundcolor=\color{codebg},
    basicstyle=\ttfamily\scriptsize,
    breakatwhitespace=false,         % sets if automatic breaks should only happen at whitespace
    breaklines=false,
    captionpos=b,                    % sets the caption-position to bottom
    commentstyle=\color{mygreen},    % comment style
    framexleftmargin=10pt,
    xleftmargin=10pt,
    framerule=0pt,
    frame=tb,                        % adds a frame around the code
    keepspaces=true,                 % keeps spaces in text, useful for keeping indentation of code (possibly needs columns=flexible)
    keywordstyle=\color{blue},       % keyword style
    showspaces=false,                % show spaces everywhere adding particular underscores; it overrides 'showstringspaces'
    showstringspaces=false,          % underline spaces within strings only
    showtabs=false,                  % show tabs within strings adding particular underscores
    stringstyle=\color{codestr},     % string literal style
    tabsize=2,                       % sets default tabsize to 2 spaces
  }
#+END_LATEX

\clearpage

* Problems

** Problem 1
   Demonstrate five distinct sets: $A$, $B$, $A \cup B$, $A \oplus B$, $A \setminus B$,
   all of which have the same cardinality.

*** Answer 1
    There's a popular programming puzzle called ``FizzBuzz''.  The taks is to
    print natural numbers according to the rule: if a number is divizible by
    three, the program prints =fizz=, if the number is divisible by five the
    program prints =buzz= (when both condition holds, the program thus prints
    =fizzbuzz=, hence the name).  Otherwise the program prints the number itself.

    It is easy to see that the description above perfectly matches the requirement:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          A             &= \{x \in \mathbb{N} \; | \; x \bmod 3 = 0\} \\
          B             &= \{x \in \mathbb{N} \; | \; x \bmod 5 = 0\} \\
          A \cup B      &= \{x \in \mathbb{N} \; | \; x \bmod 3 = 0 \lor x \bmod 5 = 0\} \\
          A \oplus B    &= \{x \in \mathbb{N} \; | \; (x \bmod 3 = 0 \lor x \bmod 5 = 0)
                            \land \lnot (x \bmod 15 = 0)\} \\
          A \setminus B &= \{x \in \mathbb{N} \; | \; x \bmod 3 = 0 \land \lnot (x \bmod 5 = 0)\}.
        \end{aligned}
      \end{equation*}
    #+END_SRC
    The cardinality of all sets is $\aleph_0$ and neither one of them is equal to any
    other set.

** Problem 2
   1. Let $n$ be a natural number. Show that the set of all subsets of $\mathbb{N}$ of
      cardinality exactly $n$ is a countable set.
   2. Show that the set of all finite subsets of $\mathbb{N}$ is countable.
   3. Show that the set of all infinite subsets of $\mathbb{N}$ is not countable.
   4. Find the cardinality of the set given in (3).
   5. $\aleph_0 = \abs{\{X \in P(\mathbb{N}) | \abs{X} = n\}}$ is the restatement of (1).
      Write a similar statement for (2) and (4).

*** Answer 2
    We can construct the set of all subsets of $\mathbb{N}$ by repeating cartesian
    product $n$ times.  Since $\abs{\mathbb{N} \times \mathbb{N}} = \aleph_0$ so
    is the $\abs{\mathbb{N}^n} = \aleph_0$ (because $n$ is finite).  Note that
    the requested sets in this case are given by the resulting ordered pairs.  I.e.
    $(x_1, (x_2, \hdots (x_{n-1}, x_n) \hdots) \in \mathbb{N}^n$.  In fact, we need
    only the unique tuples, of which there are even less.

*** Answer 3
    This continues the argument from [[Answer 2]], but constructs the sets in question
    using recursive definition: $\bigcup_{i=1}^n \mathbb{N}^i$ since there are
    no infinte exponents involved in this construction, it must describe a countable
    set.

*** Answer 4
    The set of all infinite sets can be described as $\mathbb{N}^{\mathbb{N}}$.
    We can substitute $\mathbb{N}$ for any infinite subset because any infinite
    subset of $\mathbb{N}$ is equivalent to $\mathbb{N}$, which follows from
    definition of infinite set).  Because set exponentiation is non-decreasing
    in both arguments, this set has cardinality of at least $2^{\mathbb{N}}$,
    which is the cardinality of the powerset, which, by Cantor's theorem
    is infinitely larger than any countable set.

*** Answer 5
    We just stated that the requested set is equivalent to
    $\mathbb{N}^{\mathbb{N}}$ in [[Answer 4]].  Hence its cardinality is at least
    $\mathfrak{c}$ and no greater than $2^\mathfrak{c}$.  Assuming (here and
    through the rest of the answers) continuity hypothesis is true, the
    cardinality of the set in question is $\mathfrak{c}$.

*** Answer 6
    2. can be given by: $\aleph_0 = \abs{\{X \in P(\mathbb{N}), n \in 
       \mathbb{N} | \abs{X} = n\}}$.
    4. $\aleph_0 = \abs{\{X \in P(\mathbb{N}) | \abs{X} =
       \abs{\mathbb{N}}\}}$.

** Problem 3
   Find the error in the following:
   
   #+BEGIN_QUOTE
   We shall define simmetric set difference as follows: let $k$ and $m$ be cardinalities,
   not necessarily distinct.  Define $k \oplus m$ to mean $A$ and $B$ sets for which
   $\abs{A} = k$ and $\abs{B} = m$, then the cardinality of $A \oplus B$ is the value
   of $k \oplus m$.
   #+END_QUOTE

*** Answer 7
    Since we are trying to define a /binary operation/, we must make sure that the
    result (or value) of this operation is uniquely defined.  But it is easy to see
    it is not the case, since if $\abs{A \cap B} \neq \abs{A' \cap B'}$
    while at the same time $\abs{A} = \abs{A'}$ and $\abs{B} = \abs{B'}$, we will get
    that $k \oplus m \neq k \oplus m$.  Thus our attempt at defining a ring-sum
    operation will fail.

** Problem 4
   1. Let $k_1, k_2, m_1, m_2$ be cardinalities. Prove that if $k_1 \leq k_2$ and
      $m_1 \leq m_2$ then $k_1 \times m_1 \leq k_2 \times m_2$.
   2. Prove that $\mathfrak{c} \times \aleph_0 = \mathfrak{c}$.
   3. Prove that $\mathfrak{c}^{\mathfrak{c}} = 2^{\mathfrak{c}}$.

*** Answer 8
    Recall that the product of cardinalities is defined to be the cardinality of
    cartesian product.  Also, recall that $\abs{A} \leq \abs{B}$, implies having
    an injective function from $A$ to $B$.  Now we can combine these two facts
    to build the proof.  Suppose for contradiction that it was possible that
    $k_1 \times m_1 > k_2 \times m_2$.  This would mean that for some sets $A$
    and $B$ the cartesian product with cardinality $k_1 \times m_1$ defined by
    $A \times B$ contains a pair $(a, b)$ with a property that for the chosen
    injective function from $A$ to $A'$ $a$ is not the source of any element in
    $A'$. But we are given that there is an injective function from $A'$ to $A$
    (because $k_1 \leq k_2$).  The argument for $b$ is identical.  Recall that
    the function must be defined for each element in its domain, but this stands
    in contradiction to the earlier claim that $a$ (or $b$) is not in the domain
    of this function.  Since this is not possible, the proof is complete.

*** Answer 9
    To prove $\mathfrak{c} \times \aleph_0 = \mathfrak{c}$ we can use the fact
    that there are no cardinal numbers between $\mathfrak{c}$ and $\aleph_2$.
    Also relying on the ``sandwich'' theorem, which says that if we can find a
    superset with cardinality $n$ and a subset with the cardinality $n$,
    then the cardinality of the set ``sandwiched'' in between must be $n$.
    Consider $\mathfrak{c} \leq \mathfrak{c} \times \aleph_0 \leq \mathfrak{c}
    \times \mathfrak{c}$.  We can show that $\mathfrak{c} \times \aleph_0$ is at
    least as big as $\mathfrak{c}$ since $\aleph_0$ is defined to be the
    multiplicative identity.  We can also show that $\mathfrak{c} \times
    \mathfrak{c} = \mathfrak{c}$ by perusing Cantor's theorem which proves that
    the cartesian product of an infinite set with itself has the same cardinality
    as the initial set.  Thus $\mathfrak{c} \times \aleph_0 = \mathfrak{c}$.

*** Answer 10
    Observe that $\mathfrak{c}^{\mathfrak{c}}$ is the cardinality of the set of
    all functions from a set of cardinality $\mathfrak{c}$ to itself, while
    $2^{\mathfrak{c}}$ is the cardinality of the power-set of cardinality
    $\mathfrak{c}$.  We know (from Cantor's diagonal argument) that $\abs{X} <
    \abs{P(X)}$ for all sets, this means that in particular $2^{\mathfrak{c}} <
    2^{2^\mathfrak{c}}$.  Since we know that cardinality of exponentiation is
    non-decreasing in both arguments it follows that $\mathfrak{c}^{
    \mathfrak{c}} < 2^{2^{\mathfrak{c}}}$.  And because there are no cardinal
    numbers between $X$ and $P(X)$ we can conclude that
    $\mathfrak{c}^{\mathfrak{c}} = 2^{\mathfrak{c}}$.
